# Generated by Django 3.0.8 on 2020-10-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_name', models.CharField(max_length=200)),
                ('vote_cnt', models.IntegerField(default=0)),
                ('elected', models.BooleanField()),
                ('ongoing', models.BooleanField()),
            ],
            options={
                'db_table': 'vote',
            },
        ),
    ]
