# Generated by Django 3.0.8 on 2020-09-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20200819_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='name',
        ),
    ]
